name: Build Microwalk

on:
  push:
    paths:
      - 'Microwalk*/**'
  pull_request:
    paths:
      - 'Microwalk*/**'
  workflow_dispatch:

jobs:
  build-microwalk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: |
          dotnet build Microwalk/Microwalk.csproj --configuration Release
          dotnet build Microwalk.Plugins.PinTracer/Microwalk.Plugins.PinTracer.csproj --configuration Release
          dotnet build Microwalk.Plugins.JavascriptTracer/Microwalk.Plugins.JavascriptTracer.csproj --configuration Release
          dotnet build Microwalk.Plugins.QemuKernelTracer/Microwalk.Plugins.QemuKernelTracer.csproj --configuration Release
